const BASE_URL = import.meta.env.VITE_BASE_URL || "http://localhost:4000";

export const endpoints = {
  SENDOTP_API: BASE_URL + "/api/v1/auth/sendotp",
  SIGNUP_API: BASE_URL + "/api/v1/auth/signup",
  LOGIN_API: BASE_URL + "/api/v1/auth/login",
  RESETPASSTOKEN_API: BASE_URL + "/api/v1/auth/resetPasswordToken",
  RESETPASSWORD_API: BASE_URL + "/api/v1/auth/resetPassword",
  GET_USER_DETAILS_API: BASE_URL + "/api/v1/profile/getUserDetails",
  GET_ALL_USERS_API: BASE_URL + "/api/v1/admin/getAllUser",
  UPDATE_PROFILE_API: BASE_URL + "/api/v1/profile/updateProfile",
  DELETE_PROFILE_API: BASE_URL + "/api/v1/profile/deleteProfile",
  UPLOAD_RESUME_API: BASE_URL + "/api/v1/profile/uploadResume",
  REGISTER_COMPANY_API: BASE_URL + "/api/v1/admin/registercompany",
  GET_ALL_COMPANIES_API: BASE_URL + "/api/v1/admin/showallcompany",
  GET_VISITED_COMPANIES_YEARWISE_API: BASE_URL + "/api/v1/admin/showallvisitedcompanyyearwise",
  GET_TOP_COMPANIES_API: BASE_URL + "/api/v1/admin/topcompanies",
  PLACEMENT_PERCENTAGE_BRANCHWISE_API: BASE_URL + "/api/v1/admin/placementpercentagebranchwise",
  AVERAGE_PACKAGE_BRANCHWISE_API: BASE_URL + "/api/v1/admin/averagepackagebranchwise",
  AVERAGE_PACKAGE_YEARWISE_API: BASE_URL + "/api/v1/admin/averagepackageyearwise",
  TOP_PACKAGE_STUDENTS_API: BASE_URL + "/api/v1/admin/toppackagestudents",
  TOTAL_PLACED_STUDENT_API: BASE_URL + "/api/v1/admin/totalplacedstudent",
  LAST_FOUR_BATCH_PLACEMENT_API: BASE_URL + "/api/v1/admin/lastfourbatchplacement",
  LAST_FOUR_BATCH_AVG_PLACED_API: BASE_URL + "/api/v1/admin/lastfourbatchavgplaced",
  TOTAL_STUDENT_API: BASE_URL + "/api/v1/admin/totalstudent",
  PIE_CHART_VIEW_DATA_API: BASE_URL + "/api/v1/admin/piechartviewdata",
  CREATE_DEPARTMENT_API: BASE_URL + "/api/v1/admin/createdepartment",
  MARK_PLACED_API: BASE_URL + "/api/v1/admin/markplaced",
  SHOW_ALL_STUDENT_BATCHWISE_API: BASE_URL + "/api/v1/admin/showallstudentbatchwise",
  CGPA_BASED_STUDENT_API: BASE_URL + "/api/v1/admin/cgpabasedstudent",
  ANNUAL_REPORT_API: BASE_URL + "/api/v1/admin/annualreport",
  BRANCH_STATS_API: BASE_URL + "/api/v1/admin/brachStats",
  GET_STUDENT_API: BASE_URL + "/api/v1/admin/getStudent",
  UPDATE_STUDENT_API: BASE_URL + "/api/v1/admin/updateStudent",
  DELETE_STUDENT_API: BASE_URL + "/api/v1/admin/deleteStudent",
  GET_ALL_STUDENTS_API: BASE_URL + "/api/v1/admin/getAllStudents",
  COMPANY_DETAILS_API: BASE_URL + "/api/v1/admin/companydetails",
  UPDATE_COMPANY_API: BASE_URL + "/api/v1/admin/updateCompany",
  DELETE_COMPANY_API: BASE_URL + "/api/v1/admin/deleteCompany",
};
